[project]
name = "jayrah"
version = "0.1.0"
description = "A command-line tool for managing Jira issues with FZF."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "click>=8.1.8",
  "jira2markdown>=0.1.3",
  "mcp>=1.8.0",
  "pyyaml>=6.0.2",
  "rich>=13.9.4",
  "textual>=3.2.0",
  "textual-dev>=1.7.0",
]
scripts = { jayrah = "jayrah.cli:main" }

[dependency-groups]
dev = [
  "ipython>=9.0.2",
  "isort>=6.0.1",
  "pylint>=3.3.5",
  "pytest>=8.3.5",
  "remote-pdb>=2.1.0",
  "pytest-asyncio>=1.0.0",
  "pytest-cov>=6.0.0",
]

[tool.setuptools]
py-modules = ["jayrah"]

[tool.uv]
package = true

[tool.mypy]
disable_error_code = ["import-not-found"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "R0902",                      # Too many instance attributes
  "R0903",                      # Too few public methods
  "R0917",                      # Too many positional arguments
  "C0415",                      # Import outside toplevel
  "W0613",                      # Unused argument
  "W0621",                      # Redefining name from outer scope
  "W1514",                      # Using open without explicitly specifying an encoding
  "C0414",                      # Import alias does not rename original package
  "C0104",                      # Disallowed name
  "W0612",                      # Unused variable
  "R0801",                      # Duplicate code
  "R0401",                      # Cyclic import
  "C0302",                      # Too many lines in module
  "W0718",                      # Too broad exception clause
  "line-too-long",              # Line too long
  "too-many-arguments",         # Too many arguments
  "too-many-locals",            # Too many local variables
  "missing-function-docstring",
  "missing-class-docstring",
  "too-many-branches",
  "too-many-statements",
  "arguments-differ",
]
